### ISSUE TITLE
Example code for CSS conventions

### ISSUE THREAD

**Issue by ain** [interactive-pioneers/conventions#12]
To illustrate #7 better, inline example code to CSS conventions would be nice to have, e.g.:

```css
.an__example {
  font-size: 1em;
}
```

I'd suggest every convention should conclude in an example?
